name: Generate Documents

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build by Doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
          working-directory: '.'
          doxyfile-path: 'Doxyfile'

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to
          FOLDER: html # The folder the action should deploy. Specified by HTML_OUTPUT in Doxyfile
          TARGET_FOLDER: docs
